### ISSUE TITLE
communicate servo with Ros through EtherCAT

### ISSUE THREAD

**Issue by jackros1022** [shadow-robot/ros_ethercat#55]
I am student and i want to build my own robot arm. I have finished my robot urdf file and MoveIt! setup. Now I have bought Panasonic Servo and motor(MINAS A5B EtherCAT servo drives). But i can't communicate servo with Ros and don't know which package i can use. Should i use ros_control package? Can anyone guide me? 

Any hints would be appreciated!

**Comment by guihomework** [comment]
@jackros1022  did you get an answer on that ? why did you close the issue ? It would be interesting to share the answer if you got one.
As far as I understood ros_ethercat (had to look deep into once), there is a scan of the bus to find ethercat id/class and from the id,  find a matching driver from pluginlib (https://github.com/shadow-robot/ros_ethercat/blob/c9761e61846a7cebf0d950c181fef8093c213cb2/ros_ethercat_hardware/src/ethercat_hardware.cpp#L821 ) using declared drivers  (https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/indigo-devel/sr_edc_ethercat_drivers/ethercat_device_plugin.xml) that can unpack and pack the ethercat frames into data that the host can use nicely (for control and feedback)
https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/indigo-devel/sr_edc_ethercat_drivers/pr2_etherCAT.svg

**Comment by LebinLiang** [comment]
Have you solved this question? I have also built my own robotic arm and designed my own EtherCAT controller. Currently, I can enter OP mode and perform read/write operations in TwinCAT. However, I am not sure how to connect it to ROS for control.

**Comment by guihomework** [comment]
Hi @LebinLiang, this is quite an old topic. In what I remember from this past work position, one can use ros_ethercat package but has to write the driver with your ethercat device. The ethercat driver if written correctly reads/writes (pack/unpack) commands/data from EtherCAT packets, and makes them available as resources in ros_control scheme through the RobotHW class and pluginlib. This means it should fill in a join_position and read from joint_position_command (and/or vel/effort depending on the interface you have with your hardware). If those handles are available, when the controller_manager is running, and controllers correctly configured, they access those handles to read/write into them at each control cycle.

have a look at http://wiki.ros.org/ros_control the orange part is the RobotHW you need to implement. Once this exist, you can easily use existing code (publishers and controllers), load them in the controller manager and see the data you had on TwinCAT also on ROS topics.

But maybe there are already RobotHW classes for your hardware, did you check that ?

**Comment by LebinLiang** [comment]
> Hi [@LebinLiang](https://github.com/LebinLiang), this is quite an old topic. In what I remember from this past work position, one can use ros_ethercat package but has to write the driver with your ethercat device. The ethercat driver if written correctly reads/writes (pack/unpack) commands/data from EtherCAT packets, and makes them available as resources in ros_control scheme through the RobotHW class and pluginlib. This means it should fill in a join_position and read from joint_position_command (and/or vel/effort depending on the interface you have with your hardware). If those handles are available, when the controller_manager is running, and controllers correctly configured, they access those handles to read/write into them at each control cycle.
> 
> have a look at http://wiki.ros.org/ros_control the orange part is the RobotHW you need to implement. Once this exist, you can easily use existing code (publishers and controllers), load them in the controller manager and see the data you had on TwinCAT also on ROS topics.
> 
> But maybe there are already RobotHW classes for your hardware, did you check that ?

I noticed that the ros_ethercat_model package contains many files related to EtherCAT and RobotHW. Are these example files meant to guide me in implementing my project?

**Comment by guihomework** [comment]
My memory was not fully correct. The `RobotHW` is already implemented for ethercat in this `ros_ethercat` meta_package, what you need to implement seems to be an `EthercatSlave` that this function constructs and updates (https://github.com/shadow-robot/ros_ethercat/blob/c9761e61846a7cebf0d950c181fef8093c213cb2/ros_ethercat_hardware/src/ethercat_hardware.cpp#L649) in the (calls pack and unpack). The slave itself is for instance https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/noetic-devel/sr_edc_ethercat_drivers/src/sr0x.cpp which exports an `EthercatDevice` plugin (which will be found via pluginlib automatically according to the name of the slave https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/noetic-devel/sr_edc_ethercat_drivers/ethercat_device_plugin.xml) as indicated there https://github.com/shadow-robot/ros_ethercat/blob/c9761e61846a7cebf0d950c181fef8093c213cb2/ros_ethercat_hardware/src/ethercat_hardware.cpp#L649

The `EthercatSlave` does the conversion between the ethercat data and the hardware::interface (here `RobotHW`).
For the shadow `EthercatSlave` this happens there in pack/unpack  it stores the data in its own internal class `sr_hand_lib` for instance here for the unpackstate https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/noetic-devel/sr_edc_ethercat_drivers/src/sr08.cpp#L368 which has access to the `hw` pointer (RobotHW), passed during initialization here https://github.com/shadow-robot/ros_ethercat/blob/c9761e61846a7cebf0d950c181fef8093c213cb2/ros_ethercat_hardware/src/ethercat_hardware.cpp#L354 
and obtained from the RosEthercat class that is a RobotHW itself here https://github.com/shadow-robot/ros_ethercat/blob/c9761e61846a7cebf0d950c181fef8093c213cb2/ros_ethercat_model/include/ros_ethercat_model/ros_ethercat.hpp#L113

so all in all, the EthercatSlave is the path you should look at. 

If you prefer to go through the PR2 equivalent of device/slave, this happens there for instance  think https://github.com/PR2/pr2_ethercat_drivers/blob/kinetic-devel/ethercat_hardware/src/wg05.cpp
