### ISSUE TITLE
ros_ethercat_eml is licensed under GPL

### ISSUE THREAD

**Issue by xlz** [shadow-robot/ros_ethercat#68]
https://github.com/shadow-robot/ros_ethercat/blob/kinetic-devel/ros_ethercat_eml/include/ros_ethercat_eml/ethercat_AL.h#L3-L10

Therefore this package can't be licensed under BSD and must be licensed under GPL.

**Comment by AndriyPt** [comment]
@xlz thank you for your enquire. It will be fixed soon.
