### ISSUE TITLE
Can not find ehtercat_grant in ros_ethercat_loop.

### ISSUE THREAD

**Issue by Jiongyu** [shadow-robot/ros_ethercat#82]
`rosrun ros_ethercat_loop ethercat_grant
`

[rosrun] Couldn't find executable named ethercat_grant below /home/tan/ros/pr2_ethercat/src/ros_ethercat/ros_ethercat_loop

**Comment by toliver** [comment]
`ethercat_grant` is not part of the `ros_ethercat_loop` package.

The recommended way to use it is as shown in this launchfile.
https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/kinetic-devel/sr_edc_launch/sr_edc_ros_control.launch#L73

or here:
https://github.com/shadow-robot/sr-ros-interface-ethercat/blob/kinetic-devel/sr_edc_launch/sr_edc.launch#L60-L61

Basically it is an executable that you prepend to the rosrun command.

In order for it to work, the recommended way is to install it from binaries, via:

```
sudo apt install ros-kinetic-ethercat-grant
```

More information can be found here:
https://github.com/shadow-robot/ethercat_grant/blob/kinetic-devel/README.md
